language: cpp
compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo add-apt-repository -y ppa:nocte/hexahedra
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8 libboost1.54-all-dev libcrypto++-dev libleveldb-dev libenet-dev libluajit-5.1-dev zlib1g-dev librhea1-dev libglm-dev git flex bison
 - export CXX=g++-4.8 
 - export CC=gcc-4.8

script: 
 - git clone https://github.com/Nocte-/hexanoise.git
 - mkdir hexanoise-build
 - cd hexanoise-build
 - cmake ../hexanoise
 - make
 - sudo make install
 - cd ..
 - git clone https://github.com/Nocte-/es.git
 - mkdir es-build
 - cd es-build
 - cmake ../es
 - make
 - sudo make install
 - cd ..
 - mkdir build
 - cd build
 - cmake -DBUILD_UNITTESTS=ON -DBUILD_SERVER=1 -DBUILD_CLIENT=0 ..
 - make 
 - cd unit_tests
 - ./unit_tests

