.\" Manpage for hexahedra-server.
.\" Contact hexahedra-maintainer@gmail.com to correct errors or typos.
.TH HEXAHEDRA-SERVER 6
.SH NAME
hexahedra-server \- Hexahedra game server

.SH SYNOPSIS
.B hexahedra-server [ OPTION ... ]

.SH DESCRIPTION
The Hexahedra server hosts a multiplayer game.

.SH OPTIONS
None

.SH SEE ALSO
hexahedra(6)

.SH BUGS
No known bugs.

.SH AUTHOR
Nocte (hexahedra-maintainer@gmail.com)

.SH WWW
http://hexahedra.net/

