IF(ENET_LIBRARY AND ENET_INCLUDE_DIR)
  # in cache already
  SET(ENET_FIND_QUIETLY TRUE)
ENDIF(ENET_LIBRARY AND ENET_INCLUDE_DIR)

find_path(ENET_INCLUDE_DIR
  enet/enet.h
  "${ENET_ROOT}/include"
  "${CMAKE_SOURCE_DIR}/../enet-1.3.11/include"
  "${CMAKE_SOURCE_DIR}/../enet/include"
  )

find_library(ENET_LIBRARY enet
  "${ENET_ROOT}"
  "${CMAKE_SOURCE_DIR}/../enet-1.3.11"
  "${CMAKE_SOURCE_DIR}/../enet"
  enet)


IF(ENET_LIBRARY AND ENET_INCLUDE_DIR)
  SET(ENET_FOUND "YES")
  IF(NOT ENET_FIND_QUIETLY)
    MESSAGE(STATUS "Found ENet: ${ENET_LIBRARY}")
  ENDIF(NOT ENET_FIND_QUIETLY)
ELSE(ENET_LIBRARY AND ENET_INCLUDE_DIR)
  IF(NOT ENET_FIND_QUIETLY)
    MESSAGE(STATUS "Warning: Unable to find ENet!")
  ENDIF(NOT ENET_FIND_QUIETLY)
ENDIF(ENET_LIBRARY AND ENET_INCLUDE_DIR)

